### ISSUE TITLE
Setting up Travis CI builds/tests

### ISSUE THREAD

**Issue by mhitza** [asilvestre/haskell-neo4j-rest-client#12]
Consider setting up Travis CI builds. Here's a `.travis.yml` that should let you get easily started

~~~yaml
language: haskell
services:
  - neo4j
ghc:
  - 7.10
  - 7.8
~~~

**Comment by asilvestre** [comment]
Thanks! I had no idea about travis and it's really cool.

I had to overcome some problems but now I'm stucked because haskell-src-exts doesn't compile in travis I think alex and happy are old in travis' containers.

**Comment by mhitza** [comment]
As far as ghc 7.10 errors go, apparently it's a yaml parsing error https://github.com/travis-ci/travis-ci/issues/3539

Maybe with that fixed, at least those versions build successfully?

**Comment by asilvestre** [comment]
Thanks for all the help, now all tests are passing in travis so I'm closing the issue
