### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by mdgriffith** [asilvestre/haskell-neo4j-rest-client#15]
I wanted to use your library with stack, but I noticed that it hasn't been added to [stackage](http://www.stackage.org/) yet.  I was wondering if you could submit it?

You just have to make a pull request with a line stating that this package should be included and that you are the maintainer:
https://github.com/fpco/stackage/#get-your-package-included

You might want to build the package with [stackage](http://www.stackage.org/) first to see if it builds properly. 

Thanks!

**Comment by asilvestre** [comment]
Hi, I had no idea about stackage, I will take some time in the weekend to submit it.

Thanks!

**Comment by mdgriffith** [comment]
I was able to get some free time and double check that this builds with stack...which it does!

Here's the procedure I used:
```bash
cabal install stack
# cd in your current haskell-neo4j-rest-client directory
stack init
stack build
stack test
#         Test Cases    Total        
# Passed  131           131          
# Failed  0             0            
# Total   131           131  
```
As long as you have neo4j running and disable auth.

So, I think all you have to do is submit your name as the package maintainer and the name of the package to a yaml file: https://github.com/fpco/stackage/#get-your-package-included

**Comment by asilvestre** [comment]
Thank you so much, I'm sorry I didn't do it before I've got some really busy days...
I've just made the pull request https://github.com/fpco/stackage/pull/700

**Comment by mdgriffith** [comment]
No worries at all!  Thanks!
